### ISSUE TITLE
Can't seem to use WebGLRipper on Opera

### ISSUE THREAD

**Issue by OktoberfestThePlayer** [Rilshrink/WebGLRipper#12]
So I recently installed this addon on Opera because I'm interested in ripping a 3d model from avatarsdk.com which uses WebGL on their site, but whenever I hit the Insert Key nothing happens, tried doing it on Chrome and Firefox but nothing as well. Can anybody help me with this?!

Thank You!

**Comment by Rilshrink** [comment]
avatarsdk.com seems to use unity, which I believe compiles to web assembly, which this extension doesn't currently support.
