### ISSUE TITLE
Errors in manifest.json

### ISSUE THREAD

**Issue by jumpjack** [Rilshrink/WebGLRipper#16]
These parts cause error in Chrome  118.0.5993.71  for Win 10, but if I remove them, extension does not work:
```
	"browser_specific_settings": {
	  "gecko": {
		"id": "rilshrink@webglripper"
	  }
```

and 

```
	"permissions": [
		"<all_urls>",
```

Errors:

webglripper.js:192 Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at chrome-extension://hjefjplcjccbilpchbanejhpooohmgmm/webglripper.js:192:29

webglripper.js:192 Uncaught DOMException: Blocked a frame with origin "https://oilviscositychart.com" from accessing a cross-origin frame.
    at chrome-extension://hjefjplcjccbilpchbanejhpooohmgmm/webglripper.js:192:29

Then it prints  "WebGLRipper] Capturing scene!", but nothing happens.

Tested on: https://evolventdesign.com/pages/gear-stl-generator

**Comment by Rilshrink** [comment]
Should be fixed
