### ISSUE TITLE
Breaks turbowarp.org

### ISSUE THREAD

**Issue by GarboMuffin** [Rilshrink/WebGLRipper#21]
When WebGLRipper is installed and "Shader Calc" is enabled, https://turbowarp.org/editor can no longer render the stage. This was found because one of your users was no longer able to use our site https://github.com/TurboWarp/scratch-gui/issues/920. There are more logs inside that issue but the important error is:

![image](https://github.com/Rilshrink/WebGLRipper/assets/33787854/c84998f4-30eb-4765-8c07-4bfa6aa31b2a)

I don't know what your project does but maybe you want to fix that? Thanks.

turbowarp.org now detects this option and throws up an error screen, so for debugging purposes you can use https://turbowarp.org/editor?ignore_unsupported_userscripts=i_will_not_ask_for_help_if_something_breaks instead to skip the error

**Comment by GarboMuffin** [comment]
It is because we use WebGL 1. You try to force using WebGL 2 here:

https://github.com/Rilshrink/WebGLRipper/blob/5d886ef026ac56a1bab3ff91c6c666686e80769f/webglripper.js#L1345-L1347

however that does not work because isDoShaderCalc only gets initialized when DOMContentLoaded fires:

https://github.com/Rilshrink/WebGLRipper/blob/5d886ef026ac56a1bab3ff91c6c666686e80769f/webglripper.js#L222-L229

but we create our WebGL context way before that, so now you have a WebGL 1 context that you try running WebGL 2 functions on. This same bug will break a lot of other websites.

**Comment by Rilshrink** [comment]
Sorry about that; I didn't include a disclaimer about reporting issues or about the work-in-progress (WIP) nature of the shader calculator. I potentially fixed the race condition with loading settings—thanks for reporting that. As this extension is used to 'rip' 3D objects from WebGL by hooking various methods and storing the WebGL state to attempt to convert it into the proper 3D objects, it does come with limitations, of course. Currently, I don't support the 2D version of WebGL; it only supports 3D coordinates for vertices.

**Comment by GarboMuffin** [comment]
Thank you
