### ISSUE TITLE
Feature Request: Adjust size of Texture Buffer

### ISSUE THREAD

**Issue by DMJC** [Rilshrink/WebGLRipper#4]
This is a feature request, where the extension is using 4096x4096. Can we set that as a user-changeable variable? I've been ripping content with low resolution textures and 4096x4096 is a really high value to create every texture at. Most of the textures I've been extracting are 256x256 or smaller. A setting that can be changed by users to increase/decrease the texture size from 256x256 to 16384x16384 would give the most flexibility.

**Comment by Rilshrink** [comment]
Great suggestions will be working on it ASAP!
