### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by DMJC** [Rilshrink/WebGLRipper#5]
I have a manifest file which works in Firefox, the plugin loads and executes, but I am hitting a security issue.

Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://www.wcnews.com/e8f612ca-3790-48b8-bf0f-b9e5082f9c5b (“default-src”). shipviewer
Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://www.wcnews.com/a65326da-75b7-426a-b073-52772ec4812a (“default-src”). shipviewer
Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://www.wcnews.com/c40d0f33-16ce-4a76-8696-e99cfea878e7 (“default-src”). shipviewer
Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://www.wcnews.com/29d10ffc-622d-4511-b53b-6819974f3ed3 (“default-src”). shipviewer
Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://www.wcnews.com/3a2c0071-30a5-49e5-baea-693a1b10949b (“default-src”). shipviewer
Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://www.wcnews.com/c99800c0-8442-4d1c-b635-8360ac4a592a (“default-src”).

I did some research and it sounds like the CSP policy should auto-bypass for a browser extension but I haven't figured out howto activate it yet.

**Comment by Rilshrink** [comment]
Added Firefox support, hopefully that fixes your issue.
